1 : (keyword)    : "import"
1 : (keyword)    : "from"
1 : (keyword)    : "func"
1 : (keyword)    : "class"
1 : (keyword)    : "method"
1 : (keyword)    : "self"
2 : (keyword)    : "if"
2 : (keyword)    : "elif"
2 : (keyword)    : "else"
2 : (keyword)    : "while"
2 : (keyword)    : "for"
2 : (keyword)    : "return"
2 : (keyword)    : "break"
2 : (keyword)    : "continue"
3 : (keyword)    : "true"
3 : (keyword)    : "false"
4 : (keyword)    : "int"
4 : (keyword)    : "float"
4 : (keyword)    : "string"
4 : (keyword)    : "bool"
4 : (keyword)    : "void"
6 : (symbol)     : "+"
6 : (symbol)     : "-"
6 : (symbol)     : "*"
6 : (symbol)     : "/"
6 : (symbol)     : "%"
7 : (symbol)     : "=="
7 : (symbol)     : "!="
7 : (symbol)     : "<"
7 : (symbol)     : ">"
7 : (symbol)     : "<="
7 : (symbol)     : ">="
8 : (symbol)     : "&&"
8 : (symbol)     : "||"
9 : (symbol)     : "="
9 : (symbol)     : "+="
9 : (symbol)     : "-="
9 : (symbol)     : "*="
9 : (symbol)     : "/="
9 : (symbol)     : "%="
10: (symbol)     : ";"
10: (symbol)     : ","
10: (symbol)     : "("
10: (symbol)     : ")"
10: (symbol)     : "{"
10: (symbol)     : "}"
10: (symbol)     : "."
10: (symbol)     : "["
10: (symbol)     : "]"
12: (integer)    : "12345"
12: (float)      : "123.456"
12: (string)     : "hello world"
13: (identifier) : "my_identifier"
13: (identifier) : "_another_identifier"
13: (identifier) : "MyClass123"
15: (comment)    : " abc"
16: (string)     : "/*"
17: (comment)    : """
18: (string)     : "abc"
20: (symbol)     : "+"
20: (symbol)     : "-"
20: (symbol)     : "*"
20: (symbol)     : "/"
20: (symbol)     : "%="
20: (symbol)     : "="
20: (symbol)     : "!="
20: (symbol)     : "<"
20: (symbol)     : ">"
20: (symbol)     : "<="
20: (symbol)     : ">="
20: (symbol)     : "&&"
20: (symbol)     : "||"
20: (string)     : "[][][]"
20: (symbol)     : "="
20: (symbol)     : "+="
20: (symbol)     : "-="
20: (symbol)     : "*"
20: (comment)    : "{}{}{}"
20: (symbol)     : "="
20: (symbol)     : "/="
20: (symbol)     : "%="
20: (symbol)     : ";"
20: (symbol)     : ","
20: (symbol)     : "("
20: (symbol)     : ")"
20: (symbol)     : "{"
20: (symbol)     : "}"
20: (symbol)     : "."
20: (symbol)     : "["
20: (symbol)     : "]"
20: (eof)        : ""
