gcc -Wall -E -I"include" "D:\TC\src\compiler.c" -o "./build/compiler.i"
gcc -Wall -E -I"include" "D:\TC\src\create.c" -o "./build/create.i"
gcc -Wall -E -I"include" "D:\TC\src\file.c" -o "./build/file.i"
gcc -Wall -E -I"include" "D:\TC\src\helper.c" -o "./build/helper.i"
gcc -Wall -E -I"include" "D:\TC\src\lexer.c" -o "./build/lexer.i"
gcc -Wall -E -I"include" "D:\TC\src\lib.c" -o "./build/lib.i"
gcc -Wall -E -I"include" "D:\TC\src\main.c" -o "./build/main.i"
gcc -Wall -E -I"include" "D:\TC\src\output.c" -o "./build/output.i"
gcc -Wall -E -I"include" "D:\TC\src\parser.c" -o "./build/parser.i"

gcc -Wall -S -O0 -I"include" "D:\TC\src\compiler.c" -o "./build/O0/s/compiler.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\create.c" -o "./build/O0/s/create.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\file.c" -o "./build/O0/s/file.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\helper.c" -o "./build/O0/s/helper.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\lexer.c" -o "./build/O0/s/lexer.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\lib.c" -o "./build/O0/s/lib.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\main.c" -o "./build/O0/s/main.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\output.c" -o "./build/O0/s/output.s"
gcc -Wall -S -O0 -I"include" "D:\TC\src\parser.c" -o "./build/O0/s/parser.s"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\compiler.c" -o "./build/O0/commentS/compiler.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\create.c" -o "./build/O0/commentS/create.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\file.c" -o "./build/O0/commentS/file.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\helper.c" -o "./build/O0/commentS/helper.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\lexer.c" -o "./build/O0/commentS/lexer.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\lib.c" -o "./build/O0/commentS/lib.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\main.c" -o "./build/O0/commentS/main.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\output.c" -o "./build/O0/commentS/output.S"
gcc -Wall -S -O0 -fverbose-asm -I"include" "D:\TC\src\parser.c" -o "./build/O0/commentS/parser.S"

gcc -Wall -S -O1 -I"include" "D:\TC\src\compiler.c" -o "./build/O1/s/compiler.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\create.c" -o "./build/O1/s/create.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\file.c" -o "./build/O1/s/file.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\helper.c" -o "./build/O1/s/helper.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\lexer.c" -o "./build/O1/s/lexer.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\lib.c" -o "./build/O1/s/lib.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\main.c" -o "./build/O1/s/main.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\output.c" -o "./build/O1/s/output.s"
gcc -Wall -S -O1 -I"include" "D:\TC\src\parser.c" -o "./build/O1/s/parser.s"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\compiler.c" -o "./build/O1/commentS/compiler.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\create.c" -o "./build/O1/commentS/create.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\file.c" -o "./build/O1/commentS/file.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\helper.c" -o "./build/O1/commentS/helper.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\lexer.c" -o "./build/O1/commentS/lexer.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\lib.c" -o "./build/O1/commentS/lib.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\main.c" -o "./build/O1/commentS/main.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\output.c" -o "./build/O1/commentS/output.S"
gcc -Wall -S -O1 -fverbose-asm -I"include" "D:\TC\src\parser.c" -o "./build/O1/commentS/parser.S"

gcc -Wall -S -O2 -I"include" "D:\TC\src\compiler.c" -o "./build/O2/s/compiler.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\create.c" -o "./build/O2/s/create.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\file.c" -o "./build/O2/s/file.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\helper.c" -o "./build/O2/s/helper.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\lexer.c" -o "./build/O2/s/lexer.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\lib.c" -o "./build/O2/s/lib.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\main.c" -o "./build/O2/s/main.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\output.c" -o "./build/O2/s/output.s"
gcc -Wall -S -O2 -I"include" "D:\TC\src\parser.c" -o "./build/O2/s/parser.s"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\compiler.c" -o "./build/O2/commentS/compiler.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\create.c" -o "./build/O2/commentS/create.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\file.c" -o "./build/O2/commentS/file.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\helper.c" -o "./build/O2/commentS/helper.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\lexer.c" -o "./build/O2/commentS/lexer.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\lib.c" -o "./build/O2/commentS/lib.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\main.c" -o "./build/O2/commentS/main.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\output.c" -o "./build/O2/commentS/output.S"
gcc -Wall -S -O2 -fverbose-asm -I"include" "D:\TC\src\parser.c" -o "./build/O2/commentS/parser.S"

gcc -Wall -S -O3 -I"include" "D:\TC\src\compiler.c" -o "./build/O3/s/compiler.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\create.c" -o "./build/O3/s/create.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\file.c" -o "./build/O3/s/file.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\helper.c" -o "./build/O3/s/helper.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\lexer.c" -o "./build/O3/s/lexer.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\lib.c" -o "./build/O3/s/lib.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\main.c" -o "./build/O3/s/main.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\output.c" -o "./build/O3/s/output.s"
gcc -Wall -S -O3 -I"include" "D:\TC\src\parser.c" -o "./build/O3/s/parser.s"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\compiler.c" -o "./build/O3/commentS/compiler.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\create.c" -o "./build/O3/commentS/create.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\file.c" -o "./build/O3/commentS/file.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\helper.c" -o "./build/O3/commentS/helper.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\lexer.c" -o "./build/O3/commentS/lexer.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\lib.c" -o "./build/O3/commentS/lib.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\main.c" -o "./build/O3/commentS/main.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\output.c" -o "./build/O3/commentS/output.S"
gcc -Wall -S -O3 -fverbose-asm -I"include" "D:\TC\src\parser.c" -o "./build/O3/commentS/parser.S"

gcc -Wall -S -Os -I"include" "D:\TC\src\compiler.c" -o "./build/Os/s/compiler.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\create.c" -o "./build/Os/s/create.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\file.c" -o "./build/Os/s/file.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\helper.c" -o "./build/Os/s/helper.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\lexer.c" -o "./build/Os/s/lexer.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\lib.c" -o "./build/Os/s/lib.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\main.c" -o "./build/Os/s/main.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\output.c" -o "./build/Os/s/output.s"
gcc -Wall -S -Os -I"include" "D:\TC\src\parser.c" -o "./build/Os/s/parser.s"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\compiler.c" -o "./build/Os/commentS/compiler.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\create.c" -o "./build/Os/commentS/create.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\file.c" -o "./build/Os/commentS/file.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\helper.c" -o "./build/Os/commentS/helper.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\lexer.c" -o "./build/Os/commentS/lexer.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\lib.c" -o "./build/Os/commentS/lib.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\main.c" -o "./build/Os/commentS/main.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\output.c" -o "./build/Os/commentS/output.S"
gcc -Wall -S -Os -fverbose-asm -I"include" "D:\TC\src\parser.c" -o "./build/Os/commentS/parser.S"
